name = "RustRegex"
uuid = "cdf36688-0c6d-42c6-a883-5d2df16e9e88"
authors = ["chengchingwen <chengchingwen214@gmail.com> and contributors"]
version = "0.1.0"

[deps]
rure_jll = "2a13b4fb-3cbe-5d55-9db2-86fcb16976f1"

[compat]
rure_jll = "0.2.2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
